### ISSUE TITLE
Nie działa z nową stroną Lux Medu

### ISSUE THREAD

**Issue by dkodr** [mstachniuk/LuxLekarz#10]
Od pewnego czasu Lux Med ma nowy wygląd wyszukiwarki usług. Wtyczka nie działa na nim.

![image](https://user-images.githubusercontent.com/6025373/74739250-bfff4a00-5258-11ea-8dc1-03b33176da25.png)

**Comment by mstachniuk** [comment]
Dzięki za zgłoszenie. 
Jak dojść do tego widoku? Ja po zalogowaniu do Portalu Pacienta wciąż widzę starą wyszukiwarkę, gdzie wtyczka dalej działa.

**Comment by mstachniuk** [comment]
Sprawdziłem u innej osoby i wygląda że część użytkowników ma włączony nowy UI, a ja mam jeszcze stary :-( Tak więc PR welcome (pewnie trzeba tylko kilka XPathów dopasować), albo poczekać aż będę miał na czym testować.

**Comment by dkodr** [comment]
Ok, spróbuję rzucić na to okiem ;-)

**Comment by quezak** [comment]
Cześć, super pomysł na wtyczkę!
Minęło trochę czasu, już pewnie wszyscy mają nowy interfejs, może teraz da się zaktualizować łatwiej?

// P.S. czy zrobienie kopii pod firefoxa by było w miarę łatwe czy wymagało kompletnego przepisania?

**Comment by mstachniuk** [comment]
Cześć.
Niestety w międzyczasie zrezygnowałem w LuxMeda i nie mam jak testować:-( Jak wystawisz PR to chętnie zmerguje w ciemno. Pewnie jakieś XPathy trzeba poprawić.
Przerobienie na FF nie powinno być ciężkie, ktoś już o to pytał w jakimś issue, ale nie wiem czy coś ostatecznie powstało.

**Comment by quezak** [comment]
OK, spróbuję podłubać przy świętach :)
