### ISSUE TITLE
Wyświetlanie gwiazdek przy zmianie terminu wizyty

### ISSUE THREAD

**Issue by kingablaszczynska** [mstachniuk/LuxLekarz#2]
Gwiazdki nie wyświetlają się przy wyszukiwaniu za pomocą opcji zmiany terminu obecnej wizyty:
![zmientermin](https://user-images.githubusercontent.com/25906027/38095875-c998ed9e-3371-11e8-9e6a-1db8b56390a2.png)

**Comment by mstachniuk** [comment]
URL do dodania: https://portalpacjenta.luxmed.pl/PatientPortal/Reservations/Reservation/SearchVisitsForChangeTerm

**Comment by mstachniuk** [comment]
Fixed in 1.4
