### ISSUE TITLE
Problem z działaniem (brak gwiazdek)

### ISSUE THREAD

**Issue by goostleek** [mstachniuk/LuxLekarz#5]
![image](https://user-images.githubusercontent.com/7780330/53405221-a87be100-39b7-11e9-88bc-acbc1a80d41f.png)

**Comment by mstachniuk** [comment]
Dzieki za zgloszenie. Jakis czas temu LuxMed zmienil sposob dzialania przycisku "Szukaj" i juz sie nie laduje cala strona, tylko wyniki wyszukiwania. Jak znajde czas to poprawie, chyba ze sam chcesz zrobic Pull Requesta?

**Comment by goostleek** [comment]
Super! Nie będzie to prędko, bo muszę wygospodarować czas. Pluginów do Chrome jeszcze nie obrabiałem, także chętnie zgłębię temat. Jak zacznę działać to dam znać w komentarzu, żebyśmy sobie nie przeszkadzali w przypadku gdybyś prędzej zaczął działać w temacie :)

**Comment by mstachniuk** [comment]
Naprawione w wersji 1.5
