### ISSUE TITLE
Extension for Medicover

### ISSUE THREAD

**Issue by tomekwszelaki** [mstachniuk/LuxLekarz#9]
Hi,

I didn't know how else to contact you, so I decided to create an issue here. Sorry for any inconvenience. I'd like to make a very similar thing for Medicover and I wanted to ask what's deployed under `https://docplanner-3.algolia.io/1/indexes/pl_autocomplete_doctor/query`? Is that an API you created? how could I get a unique API key? Also, would you be ok if I forked your repo and modified it to suit medicover webpage?

Thanks!
Tomek

**Comment by mstachniuk** [comment]
Hi, Sure you can fork or create PR to this repo to support both services. It's open source. 
The `docplanner-3.algolia.io` is a part of ZnanyLekarz.pl search engine.

**Comment by tomekwszelaki** [comment]
Thanks!
